using Microsoft.Win32.SafeHandles;
using PearlCalculatorLib.General;
using PearlCalculatorLib.PearlCalculationLib.Entity;
using PearlCalculatorLib.PearlCalculationLib.World;
using System;
using System.Dynamic;
using System.IO;
using System.Runtime.InteropServices.WindowsRuntime;
using System.Text.Encodings.Web;
using System.Text.Json;

namespace PCCSettingsGenerator
{
    class Program
    {
        private static readonly SettingsJsonConverter JsonConverter = new SettingsJsonConverter();

        private static JsonSerializerOptions WriteSerializerOptions = new JsonSerializerOptions
        {
            Converters = { JsonConverter } ,
            WriteIndented = true
        };


        static void Main(string[] args)
        {
            string temp = "Start";
            Console.WriteLine("Welcome to use Pearl Calculator Core Settings Generator.");
            Console.WriteLine("Note :");
            Console.WriteLine("The settings generated by this applidcation will have a percision lost.");
            Console.WriteLine("Please keed this in mind.");
            Console.WriteLine("If you stil perfer using this application");
            Console.WriteLine("Press any key to proceed.");
            Console.ReadKey();
            PearlCalculatorLib.General.Settings settings = new PearlCalculatorLib.General.Settings
            {
                Pearl = new PearlEntity() ,
                Offset = new Surface2D()
            };
            PearlEntity pearl = new PearlEntity();
            Surface2D chamber = new Surface2D();
            do
            {
                if(temp == "1" || temp == "Start")
                {
                    Console.WriteLine("Please enter the center Of your FTL blast chamber :");
                    chamber = ReadSurface2DFromConsole("FTL blast chamber ceter");
                }
                if(temp == "2" || temp == "Start")
                {
                    Console.WriteLine("Please enter the pearl coordinate :");
                    settings.Pearl.Position = ReadSpace3DFromConsole("Pearl position");
                }
                if(temp == "3" || temp == "Start")
                {
                    Console.WriteLine("Please enter the pearl motion :");
                    settings.Pearl.Motion = ReadSpace3DFromConsole("Pearl Motion");
                }
                if(temp == "4" || temp == "Start")
                {
                    Console.WriteLine("Please enter the north west TNT coordinate :");
                    settings.NorthWestTNT = ReadSpace3DFromConsole("North west TNT position");
                }
                if(temp == "5" || temp == "Start")
                {
                    Console.WriteLine("Please enter the north east TNT coordinate :");
                    settings.NorthEastTNT = ReadSpace3DFromConsole("North east TNT position");
                }
                if(temp == "6" || temp == "Start")
                {
                    Console.WriteLine("Please enter the south west TNT coordinate :");
                    settings.SouthWestTNT = ReadSpace3DFromConsole("South west TNT position");
                }
                if(temp == "7" || temp == "Start")
                {
                    Console.WriteLine("Please enter the south east TNT coordinate :");
                    settings.SouthEastTNT = ReadSpace3DFromConsole("South east TNT position");
                }
                if(temp == "8" || temp == "Start")
                {
                    Console.WriteLine("Please enter the max TNT :");
                    temp = Console.ReadLine();
                    while(!int.TryParse(temp , out settings.MaxTNT))
                    {
                        Console.WriteLine("Format Error. Please enter the following value again.");
                        Console.WriteLine("Max TNT :");
                        temp = Console.ReadLine();
                    }
                }
                Console.WriteLine("This is the value you have entered.");
                Console.WriteLine("1) FTL blast chamber center " + chamber);
                Console.WriteLine("2) Ender Pearl " + settings.Pearl.Position);
                temp = settings.Pearl.Motion.X.ToString() + " , " + settings.Pearl.Motion.Y.ToString() + " , " + pearl.Motion.Z.ToString();
                Console.WriteLine("3) Ender Pearl motion : " + temp);
                Console.WriteLine("4) North west TNT " + settings.NorthWestTNT);
                Console.WriteLine("5) North east TNT " + settings.NorthEastTNT);
                Console.WriteLine("6) South west TNT " + settings.SouthWestTNT);
                Console.WriteLine("7) South east TNT " + settings.SouthEastTNT);
                Console.WriteLine("8) Max TNT : " + settings.MaxTNT.ToString());
                Console.WriteLine("Please confirm if it is all correct. (Y/N)");
                temp = Console.ReadLine().ToUpper();
                while(temp != "Y" && temp != "N")
                {
                    Console.WriteLine("Unexpected anser. Please confirm if it is all correct. (Y/N)");
                    temp = Console.ReadLine().ToUpper();
                }
                if(temp == "N")
                {
                    Console.WriteLine("Which value you want to chamge.");
                    Console.WriteLine("Please type the number of it.");
                    temp = Console.ReadLine();
                    while(!(int.TryParse(temp , out int i) && i < 9 && i > 0))
                    {
                        Console.WriteLine("Format Error. Please enter the following value again.");
                        Console.WriteLine("Which value you want to chamge.");
                        Console.WriteLine("Please type the number of it.");
                        temp = Console.ReadLine();
                    }
                }
            } while(temp != "Y");
            settings.NorthWestTNT -= chamber.ToSpace3D();
            settings.NorthEastTNT -= chamber.ToSpace3D();
            settings.SouthWestTNT -= chamber.ToSpace3D();
            settings.SouthEastTNT -= chamber.ToSpace3D();
            settings.Offset = settings.Pearl.Position.ToSurface2D() - chamber;
            settings.Pearl.Position.X = 0;
            settings.Pearl.Position.Z = 0;
            Console.WriteLine("This is the setting it generated.");
            Console.WriteLine("1) Max TNT : " + settings.MaxTNT.ToString());
            Console.WriteLine("2) North West TNT " + settings.NorthWestTNT.ToString());
            Console.WriteLine("3) North East TNT " + settings.NorthEastTNT.ToString());
            Console.WriteLine("4) South West TNT " + settings.SouthWestTNT.ToString());
            Console.WriteLine("5) South East TNT " + settings.SouthEastTNT.ToString());
            Console.WriteLine("6) Ender Pearl Height : " + settings.Pearl.Position.Y.ToString());
            temp = settings.Pearl.Motion.X.ToString() + " , " + settings.Pearl.Motion.Y.ToString() + " , " + settings.Pearl.Motion.Z.ToString();
            Console.WriteLine("7) Ender Pearl Motion : " + temp);
            Console.WriteLine("8) Offset " + settings.Offset.ToString());
            Console.WriteLine("Do you want to output as an settings.json? (Y/N)");
            temp = Console.ReadLine().ToUpper();
            while(temp != "Y" && temp != "N")
            {
                Console.WriteLine("Unexpected anser. Do you want to output as an settings.json? (Y/N)");
                temp = Console.ReadLine().ToUpper();
            }
            if(temp == "Y")
            {
                SaveSettingsToJson("./settings.json" , settings);
                Console.WriteLine("Settings file generated.");
            }
            Console.WriteLine("Press any key to exit the application.");
            Console.ReadKey();
        }

        private static void SaveSettingsToJson(string path , Settings settings)
        {
            var json = JsonSerializer.SerializeToUtf8Bytes(settings , WriteSerializerOptions);

            using var sr = File.OpenWrite(path);
            sr.SetLength(0);
            sr.Write(json.AsSpan());
        }


        public static Space3D ReadSpace3DFromConsole(string valueName)
        {
            Space3D result;
            Console.WriteLine(valueName + " X :");
            string temp = Console.ReadLine();
            while(!double.TryParse(temp , out result.X))
            {
                Console.WriteLine("Format Error. Please enter the following value again.");
                Console.WriteLine(valueName + " X :");
                temp = Console.ReadLine();
            }
            Console.WriteLine(valueName + " Y :");
            temp = Console.ReadLine();
            while(!double.TryParse(temp , out result.Y))
            {
                Console.WriteLine("Format Error. Please enter the following value again.");
                Console.WriteLine(valueName + " X :");
                temp = Console.ReadLine();
            }
            Console.WriteLine(valueName + " Z :");
            temp = Console.ReadLine();
            while(!double.TryParse(temp , out result.Z))
            {
                Console.WriteLine("Format Error. Please enter the following value again.");
                Console.WriteLine(valueName + " Z :");
                temp = Console.ReadLine();
            }
            return result;
        }

        public static Surface2D ReadSurface2DFromConsole(string valueName)
        {
            Surface2D result = new Surface2D();
            Console.WriteLine(valueName + " X :");
            string temp = Console.ReadLine();
            while(!double.TryParse(temp , out result.X))
            {
                Console.WriteLine("Format Error. Please enter the following value again.");
                Console.WriteLine(valueName + " X :");
                temp = Console.ReadLine();
            }
            Console.WriteLine(valueName + " Z :");
            temp = Console.ReadLine();
            while(!double.TryParse(temp , out result.Z))
            {
                Console.WriteLine("Format Error. Please enter the following value again.");
                Console.WriteLine(valueName + " Z :");
                temp = Console.ReadLine();
            }
            return result;
        }
    }
}
